# -*- coding: utf-8 -*-
"""join date and news.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1vt-5B9HunAbl0IFMnRXCy8_OHS2Hhohf
"""

import csv

def remove_header(fname):
  with open(fname, 'r', newline='') as file:
    rows = list(csv.reader(file))
  del rows[0]
  with open(fname, 'w', newline='') as file:
    writer = csv.writer(file)
    writer.writerows(rows)

  return fname

def append_data():
  hist_data = ["R2020_2021.csv","R2021_22.csv","R2022_23.csv","R2023_24.csv"]
  news_data = ["RI_moneycontrol.csv","RI_economictimes_1.csv","RI_economictimes_2.csv"]
  final_data = []

  for i in range(len(hist_data)):
    hist_data[i] = remove_header(hist_data[i])

  for histdata in hist_data:
    with open(histdata, 'r') as file:
      csv_reader = csv.reader(file)
      for row in csv_reader:
        final_data.append(row)
  final_data.insert(0,['Date','Open','High','Low','Close','Adj Close','Volume'])

  with open('final_hist.csv','w',newline='') as file:
    csv_writer = csv.writer(file)
    csv_writer.writerows(final_data)

  final_data = []
  for i in range(len(news_data)):
    news_data[i] = remove_header(news_data[i])

  for newsdata in news_data:
    with open(newsdata, 'r') as file:
      csv_reader = csv.reader(file)
      for row in csv_reader:
        final_data.append(row) #del row[0]

  final_data.insert(0,['Company','Date of publishing','Author','Headline','Description','Article Body','URL'])
  with open('final_news.csv','w',newline='') as file:
    csv_writer = csv.writer(file)
    csv_writer.writerows(final_data)

  check_date('final_hist.csv','final_news.csv')

def check_date(fname1, fname2):
  fd = []
  flag = 0
  merged_data = []
  with open(fname1,'r',newline='') as file:
    csv_reader = csv.reader(file)
    for row1 in csv_reader:
      date1 = row1[0]
      flag = 0
      with open(fname2,'r',newline='') as file:
        reader = csv.reader(file)
        for row2 in reader:
          date2 = row2[1][:10]
          if date2[:4]==date1[6:] and date2[5:7]==date1[3:5] and date1[:2]==date2[8:]:
            del row2[1]
            merged_data.append(row1 + row2)
            flag = 1
      if flag == 0:
        merged_data.append(row1)
      #print(row1)

  merged_data[0].extend(['Company','Author','Headline','Description','Article Body','URL'])
  print(merged_data)
  with open('merged_data.csv','w',newline = '') as file:
    csv_writer = csv.writer(file)
    csv_writer.writerows(merged_data)

append_data()

